site_name: DIaL3  <img src='/img/WhiteBlockUoLlogo.png' class="logo" alt="UoL Logo"/>
site_url: https://www630.lamp.le.ac.uk/

nav:
- Home: 'index.md'

- About:
    Architecture: './About_dial3/architecture.md'
    Filesystem: './About_dial3/filesystem.md'
    
- Getting Started:
    Create Account: './Getting_started/create_account.md'
    Connecting: './Getting_started/connecting_dial3.md'
    
- Software:
    Software Installed on DIaL3: './Software/software_installed.md'
    Software Module System: './Software/module_system.md'
    Compiling code: './Software/Compiling_code.md' 
    Python: './Software/Python.md'
     
- Running Jobs:
    Dos and Don'ts: './Run_computation/dos_and_donts.md'
    Interactive or batch: './Run_computation/interactive_or_batch.md'
    Batch System: './Run_computation/batch_system.md'
    SLURM Worload Manager: './Run_computation/Slurm_workload_manager.md'
    Interactive Job: './Run_computation/interactive_job.md'
    Job types: './Run_computation/job_types.md'
    Monitor jobs: './Run_computation/monitor_jobs.md'
    
- Analyse code using Arm Forge:
    What is Arm Forge: './Analyse_code/about_arm_forge.md'
    Install Arm Forge: './Analyse_code/Install_arm_forge.md'
    Performance Report: './Analyse_code/Perf_report.md'
    Profile your Code: './Analyse_code/Profile_code.md'
    Debug your Code: './Analyse_code/Debug_code.md'
    
- Getting Help: 
    Frequently asked questions: './Support/FAQ.md'
    Contact : './Support/Contact.md'
    Support Staff: './Support/Support_staff.md'


theme: 
  name: readthedocs
  custom_dir: custom_theme/
  extra_templates: 
    - index.html
    - base.html
